### ISSUE TITLE
Catch error during parsing JSON

### ISSUE THREAD

**Issue by loki-dv** [petrjurasek/artifactory-prometheus-exporter#7]
Hello.

I am trying to use your monitoring image to check my Artifactory installation. I use it as a part of my docker-compose file, configuration is like this:

```
...
  artifactory-exporter:
    image: petrjurasek/artifactory-prometheus-exporter
    restart: unless-stopped

    environment:
      - ARTIFACTORY_URL=http://artifactory:8081/artifactory
      - ARTIFACTORY_USER=prometheus
      - ARTIFACTORY_PASSWORD=password
      - APP_INTERVAL=15
    depends_on:
      - artifactory
...
```

Prometheus user in the Artifactory is administrator. Username and password are correct. URL is correct too. But after starting the container I catch the error:

```
2019-12-10 01:58:34 INFO: Updating metrics
2019-12-10 01:58:47 ERROR: Task exception was never retrieved
future: <Task finished coro=<update_metrics() done, defined at main.py:48> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "main.py", line 51, in update_metrics
    artifactory_metrics_updater.update(artifactory_metrics)
  File "/app/src/artifactory_metrics_updater.py", line 12, in update
    for realm, count in self.__api_client.users().items():
  File "/app/src/artifactory_api_client.py", line 13, in users
    users = self.__request('/security/users')[0]
  File "/app/src/artifactory_api_client.py", line 74, in __request
    return json.loads(response.text), response.status_code
  File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

When I try to access to the Artifactory API via /security/users I can see the user information. I use this command in my case:

```
curl -u prometheus:password http://artifactory:8081/artifactory/api/security/users
```

How I can fix this error?

Thanks.

**Comment by loki-dv** [comment]
Added a little debug, as I can see 503 returned. I printed result URL and responce:

```
http://artifactory:8081/artifactory/api/security/users
<Response [503]>
```

**Comment by peimanja** [comment]
> Added a little debug, as I can see 503 returned. I printed result URL and responce:
> 
> ```
> http://artifactory:8081/artifactory/api/security/users
> <Response [503]>
> ```

This exporter looks like has been abandoned. I had the similar issue and I wrote a the exporter in Go, you can give it a try and leave feedback as I am actively working on it https://github.com/peimanja/artifactory_exporter
