### ISSUE TITLE
None of artifactory data is retrieved getting below when run docker command with parameters given

### ISSUE THREAD

**Issue by shahabidh** [petrjurasek/artifactory-prometheus-exporter#8]
2019-12-13 03:17:34 INFO: Updating metrics
2019-12-13 03:17:36 ERROR: Task exception was never retrieved
future: <Task finished coro=<update_metrics() done, defined at main.py:48> exception=AttributeError("'str' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "main.py", line 51, in update_metrics
    artifactory_metrics_updater.update(artifactory_metrics)
  File "/app/src/artifactory_metrics_updater.py", line 12, in update
    for realm, count in self.__api_client.users().items():
  File "/app/src/artifactory_api_client.py", line 18, in users
    realm = user.get('realm', 'none')
AttributeError: 'str' object has no attribute 'get'

**Comment by peimanja** [comment]
> 2019-12-13 03:17:34 INFO: Updating metrics
> 2019-12-13 03:17:36 ERROR: Task exception was never retrieved
> future: <Task finished coro=<update_metrics() done, defined at main.py:48> exception=AttributeError("'str' object has no attribute 'get'",)>
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
> result = coro.send(None)
> File "main.py", line 51, in update_metrics
> artifactory_metrics_updater.update(artifactory_metrics)
> File "/app/src/artifactory_metrics_updater.py", line 12, in update
> for realm, count in self.__api_client.users().items():
> File "/app/src/artifactory_api_client.py", line 18, in users
> realm = user.get('realm', 'none')
> AttributeError: 'str' object has no attribute 'get'

This exporter looks like has been abandoned. I had the similar issue and I wrote a the exporter in Go, you can give it a try and leave feedback as I am actively working on it https://github.com/peimanja/artifactory_exporter
